/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductCircularInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductCircularInformationTests
    {
        // TODO uncomment below to declare an instance variable for ProductCircularInformation
        //private ProductCircularInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductCircularInformation
            //instance = new ProductCircularInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductCircularInformation
        /// </summary>
        [Test]
        public void ProductCircularInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductCircularInformation
            //Assert.IsInstanceOfType<ProductCircularInformation> (instance, "variable 'instance' is a ProductCircularInformation");
        }


        /// <summary>
        /// Test the property 'RecycledPercentageFeedstock'
        /// </summary>
        [Test]
        public void RecycledPercentageFeedstockTest()
        {
            // TODO unit test for the property 'RecycledPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'RapidRenewablesPercentageFeedstock'
        /// </summary>
        [Test]
        public void RapidRenewablesPercentageFeedstockTest()
        {
            // TODO unit test for the property 'RapidRenewablesPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'VirginPercentageFeedstock'
        /// </summary>
        [Test]
        public void VirginPercentageFeedstockTest()
        {
            // TODO unit test for the property 'VirginPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'RecycledPercentageEndOfLife'
        /// </summary>
        [Test]
        public void RecycledPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'RecycledPercentageEndOfLife'
        }
        /// <summary>
        /// Test the property 'LandfillPercentageEndOfLife'
        /// </summary>
        [Test]
        public void LandfillPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'LandfillPercentageEndOfLife'
        }
        /// <summary>
        /// Test the property 'IncinerationPercentageEndOfLife'
        /// </summary>
        [Test]
        public void IncinerationPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'IncinerationPercentageEndOfLife'
        }
        /// <summary>
        /// Test the property 'EfficiencyPercentageRecyclingFeedstock'
        /// </summary>
        [Test]
        public void EfficiencyPercentageRecyclingFeedstockTest()
        {
            // TODO unit test for the property 'EfficiencyPercentageRecyclingFeedstock'
        }
        /// <summary>
        /// Test the property 'EfficiencyPercentageRecyclingEndOfLife'
        /// </summary>
        [Test]
        public void EfficiencyPercentageRecyclingEndOfLifeTest()
        {
            // TODO unit test for the property 'EfficiencyPercentageRecyclingEndOfLife'
        }
        /// <summary>
        /// Test the property 'TechnicalLifetime'
        /// </summary>
        [Test]
        public void TechnicalLifetimeTest()
        {
            // TODO unit test for the property 'TechnicalLifetime'
        }
        /// <summary>
        /// Test the property 'FunctionalLifetime'
        /// </summary>
        [Test]
        public void FunctionalLifetimeTest()
        {
            // TODO unit test for the property 'FunctionalLifetime'
        }
        /// <summary>
        /// Test the property 'ProductReusedPercentageFeedstock'
        /// </summary>
        [Test]
        public void ProductReusedPercentageFeedstockTest()
        {
            // TODO unit test for the property 'ProductReusedPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'ProductRecycledPercentageFeedstock'
        /// </summary>
        [Test]
        public void ProductRecycledPercentageFeedstockTest()
        {
            // TODO unit test for the property 'ProductRecycledPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'ProductRapidRenewablesPercentageFeedstock'
        /// </summary>
        [Test]
        public void ProductRapidRenewablesPercentageFeedstockTest()
        {
            // TODO unit test for the property 'ProductRapidRenewablesPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'ProductVirginPercentageFeedstock'
        /// </summary>
        [Test]
        public void ProductVirginPercentageFeedstockTest()
        {
            // TODO unit test for the property 'ProductVirginPercentageFeedstock'
        }
        /// <summary>
        /// Test the property 'ProductReusedPercentageEndOfLife'
        /// </summary>
        [Test]
        public void ProductReusedPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'ProductReusedPercentageEndOfLife'
        }
        /// <summary>
        /// Test the property 'ProductRecycledPercentageEndOfLife'
        /// </summary>
        [Test]
        public void ProductRecycledPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'ProductRecycledPercentageEndOfLife'
        }
        /// <summary>
        /// Test the property 'ProductLandfillPercentageEndOfLife'
        /// </summary>
        [Test]
        public void ProductLandfillPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'ProductLandfillPercentageEndOfLife'
        }
        /// <summary>
        /// Test the property 'ProductIncinerationPercentageEndOfLife'
        /// </summary>
        [Test]
        public void ProductIncinerationPercentageEndOfLifeTest()
        {
            // TODO unit test for the property 'ProductIncinerationPercentageEndOfLife'
        }

    }

}
