/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductChild
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductChildTests
    {
        // TODO uncomment below to declare an instance variable for ProductChild
        //private ProductChild instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductChild
            //instance = new ProductChild();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductChild
        /// </summary>
        [Test]
        public void ProductChildInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductChild
            //Assert.IsInstanceOfType<ProductChild> (instance, "variable 'instance' is a ProductChild");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'ChildId'
        /// </summary>
        [Test]
        public void ChildIdTest()
        {
            // TODO unit test for the property 'ChildId'
        }
        /// <summary>
        /// Test the property 'Circular'
        /// </summary>
        [Test]
        public void CircularTest()
        {
            // TODO unit test for the property 'Circular'
        }

    }

}
