theme: jekyll-theme-cayman
title: 
  en: Madaster Documentation
  nl: Madaster Documentatie
description: 
  en: Welcome to Madaster Documentation. You can find comprehensive guides and documentation to help get you started with Madaster as quickly as possible, and support if you get stuck.
  nl: Welkom bij de documentatie website van Madaster.
plugins:
  - jekyll-toc
gems:
  - jekyll-multiple-languages-plugin
index:
  en:
  nl: thuis.html
