/*theme: jekyll-theme-cayman*/
remote_theme: chrisrhymes/bulma-clean-theme
countries:
  - country: "Nederland"
    code: "nl"
    defaultlanguage: "nl"
    languages: "nl,en"
  - country: "Swiss"
    code: "ch"
    defaultlanguage: "de"
    languages: "de,fr"
  
title: 
  en: Madaster Documentation
  nl: Madaster Documentatie
  de: Madaster Dokumentation
  fr: Documentation Madaster 

defaults:
  -
    scope :
      path: ""
    values:
      layout: "page"
      show_sidebar: false
      menubar: faq-nav
  -
    scope :
      path: "ch/de"
    values:
        lang: "de"
        country: "ch"
  -
    scope :
      path: "ch/fr"
    values:
        lang: "fr"
        country: "ch"        
  -
    scope :
      path: "nl/nl"
    values:
        country: "nl"
        lang: "nl"
  -
    scope :
      path: "nl/en"
    values:
        country: "nl"
        lang: "en"
  -
    scope :
      path: "de"
    values:
        country: "de"
        lang: "de" 
  -
    scope :
      path: "no/en"
    values:
        country: "no"
        lang: "en" 
  - 
    scope :
      path: "no/no"
    values:
        country: "no"
        lang: "no"     

  
