/*theme: jekyll-theme-cayman*/
remote_theme: chrisrhymes/bulma-clean-theme
countries:
  - country: "Nederland"
    code: "nl"
    defaultlanguage: "nl"
    languages: "nl,en"
  - country: "Swiss"
    code: "ch"
    defaultlanguage: "de"
    languages: "de,fr,en"
  - country: "Norway"
    code: "no"
    defaultlanguage: "nb"
    languages: "nb,en"
  - country: "Deutschland"
    code: "de"
    defaultlanguage: "de"
    languages: "de"
  - country: "Belgium"
    code: "be"
    defaultlanguage: "nl"
    languages: "nl,fr,en"
  - country: "Austria"
    code: "at"
    defaultlanguage: "de"
    languages: "de"
  
title: Madaster Documentation

gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from

exclude:
  - README.md
  - swagger.json
  - update-api-docs.ps1
  
defaults:
  -
    scope :
      path: ""
    values:
      layout: "page"
      show_sidebar: false
      menubar: faq-nav
  -
    scope :
      path: "ch/de"
    values:
      lang: "de"
      lang_name: "Deutsch"
      country: "ch"
  -
    scope :
      path: "ch/fr"
    values:
      lang: "fr"
      lang_name: "Français"
      country: "ch"
  -
    scope :
      path: "ch/en"
    values:
      lang: "en"
      lang_name: "English"
      country: "ch"
  -
    scope :
      path: "nl/nl"
    values:
      country: "nl"
      lang_name: "Nederlands"
      lang: "nl"
  -
    scope :
      path: "nl/en"
    values:
      country: "nl"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "de/de"
    values:
      country: "de"
      lang_name: "Deutsch"
      lang: "de"
  -
    scope :
      path: "no/en"
    values:
      country: "no"
      lang_name: "English"
      lang: "en" 
  - 
    scope :
      path: "no/nb"
    values:
      country: "no"
      lang_name: "Norsk bokmål"
      lang: "nb"     
  - 
    scope :
      path : "be/nl"
    values:
      country: "be"
      lang_name: "Nederlands"
      lang: "nl"
  - 
    scope :
      path : "be/fr"
    values:
      country: "be"
      lang_name: "Français"
      lang: "fr"
  - 
    scope :
      path : "be/en"
    values:
      country: "be"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "at/de"
    values:
      country: "at"
      lang_name: "Deutsch"
      lang: "de"
