# /*theme: jekyll-theme-cayman*/
# remote_theme: chrisrhymes/bulma-clean-theme
countries:
  - country: "Netherlands"
    code: "nl"
    defaultlanguage: "nl"
    languages: "nl,en"
  - country: "Switzerland"
    code: "ch"
    defaultlanguage: "de"
    languages: "de,fr,en"
  - country: "Norway"
    code: "no"
    defaultlanguage: "nb"
    languages: "nb,en"
  - country: "Germany"
    code: "de"
    defaultlanguage: "de"
    languages: "de"
  - country: "Belgium"
    code: "be"
    defaultlanguage: "nl"
    languages: "nl,fr,en"
  - country: "Austria"
    code: "at"
    defaultlanguage: "de"
    languages: "de"
  - country: "United Kingdom"
    code: "gb"
    defaultlanguage: "en"
    languages: "en"
  - country: "Luxembourg"
    code: "lu"
    defaultlanguage: "en"
    languages: "en"
  - country: "United States"
    code: "us"
    defaultlanguage: "en"
    languages: "en"
  
title: Madaster Documentation

whitelist:
  - jekyll-last-modified-at
plugins:
  - jekyll-last-modified-at

exclude:
  - node_modules
  - README.md
  - swagger.json
  - update-api-docs.ps1
  - generateSearchJSON.mjs
  - package.json
  - package-lock.json
  
defaults:
  -
    scope :
      path: ""
    values:
      layout: "page"
      show_sidebar: false
      menubar: platform-pages-nav
  -
    scope :
      path: "at/en"
    values:
      country: "at"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "at/de"
    values:
      country: "at"
      lang_name: "Deutsch"
      lang: "de"
  - 
    scope :
      path : "be/nl"
    values:
      country: "be"
      lang_name: "Nederlands"
      lang: "nl"
  - 
    scope :
      path : "be/fr"
    values:
      country: "be"
      lang_name: "Français"
      lang: "fr"
  - 
    scope :
      path : "be/en"
    values:
      country: "be"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "ch/de"
    values:
      lang: "de"
      lang_name: "Deutsch"
      country: "ch"
  -
    scope :
      path: "ch/fr"
    values:
      lang: "fr"
      lang_name: "Français"
      country: "ch"
  -
    scope :
      path: "ch/en"
    values:
      lang: "en"
      lang_name: "English"
      country: "ch"
  -
    scope :
      path: "de/de"
    values:
      country: "de"
      lang_name: "Deutsch"
      lang: "de"
  -
    scope :
      path: "de/en"
    values:
      country: "de"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "gb/en"
    values:
      country: "gb"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "lu/en"
    values:
      country: "lu"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "nl/nl"
    values:
      country: "nl"
      lang_name: "Nederlands"
      lang: "nl"
  -
    scope :
      path: "nl/en"
    values:
      country: "nl"
      lang_name: "English"
      lang: "en"
  -
    scope :
      path: "no/en"
    values:
      country: "no"
      lang_name: "English"
      lang: "en" 
  - 
    scope :
      path: "no/nb"
    values:
      country: "no"
      lang_name: "Norsk bokmål"
      lang: "nb"     
  -
    scope :
      path: "us/en"
    values:
      country: "us"
      lang_name: "English"
      lang: "en"
