#theme: jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme
title: 
  en: Madaster Documentation
  nl: Madaster Documentatie
description: 
  en: Welcome to Madaster Documentation. You can find comprehensive guides and documentation to help get you started with Madaster as quickly as possible, and support if you get stuck.
  nl: Welkom bij de documentatie website van Madaster.
plugins:
  - jekyll-toc
index:
  en: 
  nl: index-nl.md
