/*theme: jekyll-theme-cayman*/
remote_theme: chrisrhymes/bulma-clean-theme
countries:
  - country: "Nederland"
    code: "nl"
    defaultlanguage: "nl"
    languages: "nl,en"
  - country: "Swiss"
    code: "ch"
    defaultlanguage: "de"
    languages: "de,fr,en"
  - country: "Norway"
    code: "no"
    defaultlanguage: "nb"
    languages: "nb,en"
  - country: "Deutschland"
    code: "de"
    defaultlanguage: "de"
    languages: "de"
  - country: "Belgium"
    code: "be"
    defaultlanguage: "nl"
    languages: "nl,fr,en"
  
title: Madaster Documentation

defaults:
  -
    scope :
      path: ""
    values:
      layout: "page"
      show_sidebar: false
      menubar: faq-nav
  -
    scope :
      path: "ch/de"
    values:
        lang: "de"
        country: "ch"
  -
    scope :
      path: "ch/fr"
    values:
        lang: "fr"
        country: "ch"        
  -
    scope :
      path: "ch/en"
    values:
        lang: "en"
        country: "ch"      
  -
    scope :
      path: "nl/nl"
    values:
        country: "nl"
        lang: "nl"
  -
    scope :
      path: "nl/en"
    values:
        country: "nl"
        lang: "en"
  -
    scope :
      path: "de"
    values:
        country: "de"
        lang: "de" 
  -
    scope :
      path: "no/en"
    values:
        country: "no"
        lang: "en"  
  - 
    scope :
      path: "no/nb"
    values:
      country: "no"
      lang: "nb" 
  -
    scope :
      path: "be/nl"
    values:
        lang: "nl"
        country: "be"
  -
    scope :
      path: "be/fr"
    values:
        lang: "fr"
        country: "be"        
  -
    scope :
      path: "be/en"
    values:
        lang: "en"
        country: "be"  