/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Madaster.API.Api;
using Madaster.API.Model;
using Madaster.API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Madaster.API.Test
{
    /// <summary>
    ///  Class for testing MultiLingualString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultiLingualStringTests
    {
        // TODO uncomment below to declare an instance variable for MultiLingualString
        //private MultiLingualString instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultiLingualString
            //instance = new MultiLingualString();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultiLingualString
        /// </summary>
        [Test]
        public void MultiLingualStringInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiLingualString
            //Assert.IsInstanceOfType<MultiLingualString> (instance, "variable 'instance' is a MultiLingualString");
        }


        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

    }

}
