/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Madaster.API.Api;
using Madaster.API.Model;
using Madaster.API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Madaster.API.Test
{
    /// <summary>
    ///  Class for testing PortfolioResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PortfolioResponseTests
    {
        // TODO uncomment below to declare an instance variable for PortfolioResponse
        //private PortfolioResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PortfolioResponse
            //instance = new PortfolioResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PortfolioResponse
        /// </summary>
        [Test]
        public void PortfolioResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PortfolioResponse
            //Assert.IsInstanceOfType<PortfolioResponse> (instance, "variable 'instance' is a PortfolioResponse");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Logo'
        /// </summary>
        [Test]
        public void LogoTest()
        {
            // TODO unit test for the property 'Logo'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
