/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Madaster.API.Api;
using Madaster.API.Model;
using Madaster.API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Madaster.API.Test
{
    /// <summary>
    ///  Class for testing V11BuildingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V11BuildingRequestTests
    {
        // TODO uncomment below to declare an instance variable for V11BuildingRequest
        //private V11BuildingRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V11BuildingRequest
            //instance = new V11BuildingRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V11BuildingRequest
        /// </summary>
        [Test]
        public void V11BuildingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V11BuildingRequest
            //Assert.IsInstanceOfType<V11BuildingRequest> (instance, "variable 'instance' is a V11BuildingRequest");
        }


        /// <summary>
        /// Test the property 'ClassificationType'
        /// </summary>
        [Test]
        public void ClassificationTypeTest()
        {
            // TODO unit test for the property 'ClassificationType'
        }
        /// <summary>
        /// Test the property 'PhaseType'
        /// </summary>
        [Test]
        public void PhaseTypeTest()
        {
            // TODO unit test for the property 'PhaseType'
        }
        /// <summary>
        /// Test the property 'PortfolioId'
        /// </summary>
        [Test]
        public void PortfolioIdTest()
        {
            // TODO unit test for the property 'PortfolioId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CadastralDesignation'
        /// </summary>
        [Test]
        public void CadastralDesignationTest()
        {
            // TODO unit test for the property 'CadastralDesignation'
        }
        /// <summary>
        /// Test the property 'CadastralArea'
        /// </summary>
        [Test]
        public void CadastralAreaTest()
        {
            // TODO unit test for the property 'CadastralArea'
        }
        /// <summary>
        /// Test the property 'Parcelnumber'
        /// </summary>
        [Test]
        public void ParcelnumberTest()
        {
            // TODO unit test for the property 'Parcelnumber'
        }
        /// <summary>
        /// Test the property 'PublicLawRestriction'
        /// </summary>
        [Test]
        public void PublicLawRestrictionTest()
        {
            // TODO unit test for the property 'PublicLawRestriction'
        }
        /// <summary>
        /// Test the property 'CompletionDate'
        /// </summary>
        [Test]
        public void CompletionDateTest()
        {
            // TODO unit test for the property 'CompletionDate'
        }
        /// <summary>
        /// Test the property 'LastRenovationDate'
        /// </summary>
        [Test]
        public void LastRenovationDateTest()
        {
            // TODO unit test for the property 'LastRenovationDate'
        }
        /// <summary>
        /// Test the property 'AddressStreet'
        /// </summary>
        [Test]
        public void AddressStreetTest()
        {
            // TODO unit test for the property 'AddressStreet'
        }
        /// <summary>
        /// Test the property 'AddressHousenumber'
        /// </summary>
        [Test]
        public void AddressHousenumberTest()
        {
            // TODO unit test for the property 'AddressHousenumber'
        }
        /// <summary>
        /// Test the property 'AddressHousenumberAddition'
        /// </summary>
        [Test]
        public void AddressHousenumberAdditionTest()
        {
            // TODO unit test for the property 'AddressHousenumberAddition'
        }
        /// <summary>
        /// Test the property 'AddressZipcode'
        /// </summary>
        [Test]
        public void AddressZipcodeTest()
        {
            // TODO unit test for the property 'AddressZipcode'
        }
        /// <summary>
        /// Test the property 'AddressCity'
        /// </summary>
        [Test]
        public void AddressCityTest()
        {
            // TODO unit test for the property 'AddressCity'
        }
        /// <summary>
        /// Test the property 'AddressCountry'
        /// </summary>
        [Test]
        public void AddressCountryTest()
        {
            // TODO unit test for the property 'AddressCountry'
        }
        /// <summary>
        /// Test the property 'BuildingUsage'
        /// </summary>
        [Test]
        public void BuildingUsageTest()
        {
            // TODO unit test for the property 'BuildingUsage'
        }
        /// <summary>
        /// Test the property 'GrossSurfaceArea'
        /// </summary>
        [Test]
        public void GrossSurfaceAreaTest()
        {
            // TODO unit test for the property 'GrossSurfaceArea'
        }
        /// <summary>
        /// Test the property 'EnergyLabel'
        /// </summary>
        [Test]
        public void EnergyLabelTest()
        {
            // TODO unit test for the property 'EnergyLabel'
        }
        /// <summary>
        /// Test the property 'EnergyPerformanceCoefficient'
        /// </summary>
        [Test]
        public void EnergyPerformanceCoefficientTest()
        {
            // TODO unit test for the property 'EnergyPerformanceCoefficient'
        }
        /// <summary>
        /// Test the property 'EnergyIndex'
        /// </summary>
        [Test]
        public void EnergyIndexTest()
        {
            // TODO unit test for the property 'EnergyIndex'
        }
        /// <summary>
        /// Test the property 'ExpectedLifespan'
        /// </summary>
        [Test]
        public void ExpectedLifespanTest()
        {
            // TODO unit test for the property 'ExpectedLifespan'
        }
        /// <summary>
        /// Test the property 'ExpectedLifespanStructure'
        /// </summary>
        [Test]
        public void ExpectedLifespanStructureTest()
        {
            // TODO unit test for the property 'ExpectedLifespanStructure'
        }
        /// <summary>
        /// Test the property 'ExpectedLifespanSkin'
        /// </summary>
        [Test]
        public void ExpectedLifespanSkinTest()
        {
            // TODO unit test for the property 'ExpectedLifespanSkin'
        }
        /// <summary>
        /// Test the property 'ExpectedLifespanServices'
        /// </summary>
        [Test]
        public void ExpectedLifespanServicesTest()
        {
            // TODO unit test for the property 'ExpectedLifespanServices'
        }
        /// <summary>
        /// Test the property 'ExpectedLifespanSpacePlan'
        /// </summary>
        [Test]
        public void ExpectedLifespanSpacePlanTest()
        {
            // TODO unit test for the property 'ExpectedLifespanSpacePlan'
        }
        /// <summary>
        /// Test the property 'ExpectedLifespanStuff'
        /// </summary>
        [Test]
        public void ExpectedLifespanStuffTest()
        {
            // TODO unit test for the property 'ExpectedLifespanStuff'
        }
        /// <summary>
        /// Test the property 'BreeamLabel'
        /// </summary>
        [Test]
        public void BreeamLabelTest()
        {
            // TODO unit test for the property 'BreeamLabel'
        }
        /// <summary>
        /// Test the property 'GprLabel'
        /// </summary>
        [Test]
        public void GprLabelTest()
        {
            // TODO unit test for the property 'GprLabel'
        }
        /// <summary>
        /// Test the property 'MpgLabel'
        /// </summary>
        [Test]
        public void MpgLabelTest()
        {
            // TODO unit test for the property 'MpgLabel'
        }
        /// <summary>
        /// Test the property 'LeedLabel'
        /// </summary>
        [Test]
        public void LeedLabelTest()
        {
            // TODO unit test for the property 'LeedLabel'
        }

    }

}
