/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Madaster.API.Api;
using Madaster.API.Model;
using Madaster.API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Madaster.API.Test
{
    /// <summary>
    ///  Class for testing V11FileDownloadResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V11FileDownloadResponseTests
    {
        // TODO uncomment below to declare an instance variable for V11FileDownloadResponse
        //private V11FileDownloadResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V11FileDownloadResponse
            //instance = new V11FileDownloadResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V11FileDownloadResponse
        /// </summary>
        [Test]
        public void V11FileDownloadResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V11FileDownloadResponse
            //Assert.IsInstanceOfType<V11FileDownloadResponse> (instance, "variable 'instance' is a V11FileDownloadResponse");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'ExpirationDateTime'
        /// </summary>
        [Test]
        public void ExpirationDateTimeTest()
        {
            // TODO unit test for the property 'ExpirationDateTime'
        }

    }

}
