/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Madaster.API.Api;
using Madaster.API.Model;
using Madaster.API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Madaster.API.Test
{
    /// <summary>
    ///  Class for testing V11PortfolioFileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V11PortfolioFileResponseTests
    {
        // TODO uncomment below to declare an instance variable for V11PortfolioFileResponse
        //private V11PortfolioFileResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V11PortfolioFileResponse
            //instance = new V11PortfolioFileResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V11PortfolioFileResponse
        /// </summary>
        [Test]
        public void V11PortfolioFileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V11PortfolioFileResponse
            //Assert.IsInstanceOfType<V11PortfolioFileResponse> (instance, "variable 'instance' is a V11PortfolioFileResponse");
        }


        /// <summary>
        /// Test the property 'PortfolioId'
        /// </summary>
        [Test]
        public void PortfolioIdTest()
        {
            // TODO unit test for the property 'PortfolioId'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Test]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'LastModifiedDate'
        /// </summary>
        [Test]
        public void LastModifiedDateTest()
        {
            // TODO unit test for the property 'LastModifiedDate'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
