/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Madaster.API.Api;
using Madaster.API.Model;
using Madaster.API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Madaster.API.Test
{
    /// <summary>
    ///  Class for testing V11ValidationGraph
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V11ValidationGraphTests
    {
        // TODO uncomment below to declare an instance variable for V11ValidationGraph
        //private V11ValidationGraph instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V11ValidationGraph
            //instance = new V11ValidationGraph();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V11ValidationGraph
        /// </summary>
        [Test]
        public void V11ValidationGraphInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V11ValidationGraph
            //Assert.IsInstanceOfType<V11ValidationGraph> (instance, "variable 'instance' is a V11ValidationGraph");
        }


        /// <summary>
        /// Test the property 'GraphId'
        /// </summary>
        [Test]
        public void GraphIdTest()
        {
            // TODO unit test for the property 'GraphId'
        }
        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Test]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
