<?php
/**
 * ProductDimension
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductDimension Class Doc Comment
 *
 * @category Class
 * @description A product dimension
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductDimension implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProductDimension';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'dimension_value' => 'double',
        'dimension_type' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'dimension_value' => 'double',
        'dimension_type' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dimension_value' => 'dimensionValue',
        'dimension_type' => 'dimensionType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dimension_value' => 'setDimensionValue',
        'dimension_type' => 'setDimensionType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dimension_value' => 'getDimensionValue',
        'dimension_type' => 'getDimensionType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const DIMENSION_TYPE_0 = 0;
    const DIMENSION_TYPE_1 = 1;
    const DIMENSION_TYPE_2 = 2;
    const DIMENSION_TYPE_3 = 3;
    const DIMENSION_TYPE_4 = 4;
    const DIMENSION_TYPE_5 = 5;
    const DIMENSION_TYPE_6 = 6;
    const DIMENSION_TYPE_7 = 7;
    const DIMENSION_TYPE_8 = 8;
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDimensionTypeAllowableValues()
    {
        return [
            self::DIMENSION_TYPE_0,
            self::DIMENSION_TYPE_1,
            self::DIMENSION_TYPE_2,
            self::DIMENSION_TYPE_3,
            self::DIMENSION_TYPE_4,
            self::DIMENSION_TYPE_5,
            self::DIMENSION_TYPE_6,
            self::DIMENSION_TYPE_7,
            self::DIMENSION_TYPE_8,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dimension_value'] = isset($data['dimension_value']) ? $data['dimension_value'] : null;
        $this->container['dimension_type'] = isset($data['dimension_type']) ? $data['dimension_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDimensionTypeAllowableValues();
        if (!is_null($this->container['dimension_type']) && !in_array($this->container['dimension_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'dimension_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dimension_value
     *
     * @return double
     */
    public function getDimensionValue()
    {
        return $this->container['dimension_value'];
    }

    /**
     * Sets dimension_value
     *
     * @param double $dimension_value The value of this dimension
     *
     * @return $this
     */
    public function setDimensionValue($dimension_value)
    {
        $this->container['dimension_value'] = $dimension_value;

        return $this;
    }

    /**
     * Gets dimension_type
     *
     * @return int
     */
    public function getDimensionType()
    {
        return $this->container['dimension_type'];
    }

    /**
     * Sets dimension_type
     *
     * @param int $dimension_type The type of this dimension
     *
     * @return $this
     */
    public function setDimensionType($dimension_type)
    {
        $allowedValues = $this->getDimensionTypeAllowableValues();
        if (!is_null($dimension_type) && !in_array($dimension_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'dimension_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['dimension_type'] = $dimension_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


