<?php
/**
 * ProductChildCircularInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductChildCircularInformationTest Class Doc Comment
 *
 * @category    Class
 * @description Circular information about a product child
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductChildCircularInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductChildCircularInformation"
     */
    public function testProductChildCircularInformation()
    {
    }

    /**
     * Test attribute "inherit_feedstock_percentages"
     */
    public function testPropertyInheritFeedstockPercentages()
    {
    }

    /**
     * Test attribute "recycled_percentage_feedstock"
     */
    public function testPropertyRecycledPercentageFeedstock()
    {
    }

    /**
     * Test attribute "rapid_renewables_percentage_feedstock"
     */
    public function testPropertyRapidRenewablesPercentageFeedstock()
    {
    }

    /**
     * Test attribute "inherit_end_of_life_percentages"
     */
    public function testPropertyInheritEndOfLifePercentages()
    {
    }

    /**
     * Test attribute "recycled_percentage_end_of_life"
     */
    public function testPropertyRecycledPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "landfill_percentage_end_of_life"
     */
    public function testPropertyLandfillPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "inherit_efficiency_percentages"
     */
    public function testPropertyInheritEfficiencyPercentages()
    {
    }

    /**
     * Test attribute "efficiency_percentage_recycling_feedstock"
     */
    public function testPropertyEfficiencyPercentageRecyclingFeedstock()
    {
    }

    /**
     * Test attribute "efficiency_percentage_recycling_end_of_life"
     */
    public function testPropertyEfficiencyPercentageRecyclingEndOfLife()
    {
    }
}
