<?php
/**
 * ProductCircularInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductCircularInformationTest Class Doc Comment
 *
 * @category    Class
 * @description The circular properties of the element
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductCircularInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductCircularInformation"
     */
    public function testProductCircularInformation()
    {
    }

    /**
     * Test attribute "recycled_percentage_feedstock"
     */
    public function testPropertyRecycledPercentageFeedstock()
    {
    }

    /**
     * Test attribute "rapid_renewables_percentage_feedstock"
     */
    public function testPropertyRapidRenewablesPercentageFeedstock()
    {
    }

    /**
     * Test attribute "virgin_percentage_feedstock"
     */
    public function testPropertyVirginPercentageFeedstock()
    {
    }

    /**
     * Test attribute "recycled_percentage_end_of_life"
     */
    public function testPropertyRecycledPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "landfill_percentage_end_of_life"
     */
    public function testPropertyLandfillPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "incineration_percentage_end_of_life"
     */
    public function testPropertyIncinerationPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "efficiency_percentage_recycling_feedstock"
     */
    public function testPropertyEfficiencyPercentageRecyclingFeedstock()
    {
    }

    /**
     * Test attribute "efficiency_percentage_recycling_end_of_life"
     */
    public function testPropertyEfficiencyPercentageRecyclingEndOfLife()
    {
    }

    /**
     * Test attribute "technical_lifetime"
     */
    public function testPropertyTechnicalLifetime()
    {
    }

    /**
     * Test attribute "functional_lifetime"
     */
    public function testPropertyFunctionalLifetime()
    {
    }

    /**
     * Test attribute "product_reused_percentage_feedstock"
     */
    public function testPropertyProductReusedPercentageFeedstock()
    {
    }

    /**
     * Test attribute "product_recycled_percentage_feedstock"
     */
    public function testPropertyProductRecycledPercentageFeedstock()
    {
    }

    /**
     * Test attribute "product_rapid_renewables_percentage_feedstock"
     */
    public function testPropertyProductRapidRenewablesPercentageFeedstock()
    {
    }

    /**
     * Test attribute "product_virgin_percentage_feedstock"
     */
    public function testPropertyProductVirginPercentageFeedstock()
    {
    }

    /**
     * Test attribute "product_reused_percentage_end_of_life"
     */
    public function testPropertyProductReusedPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "product_recycled_percentage_end_of_life"
     */
    public function testPropertyProductRecycledPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "product_landfill_percentage_end_of_life"
     */
    public function testPropertyProductLandfillPercentageEndOfLife()
    {
    }

    /**
     * Test attribute "product_incineration_percentage_end_of_life"
     */
    public function testPropertyProductIncinerationPercentageEndOfLife()
    {
    }
}
