/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BuildingFileValidation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuildingFileValidationTests
    {
        // TODO uncomment below to declare an instance variable for BuildingFileValidation
        //private BuildingFileValidation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuildingFileValidation
            //instance = new BuildingFileValidation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuildingFileValidation
        /// </summary>
        [Test]
        public void BuildingFileValidationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuildingFileValidation
            //Assert.IsInstanceOfType<BuildingFileValidation> (instance, "variable 'instance' is a BuildingFileValidation");
        }


        /// <summary>
        /// Test the property 'PercentageClassificationAssignedByNumber'
        /// </summary>
        [Test]
        public void PercentageClassificationAssignedByNumberTest()
        {
            // TODO unit test for the property 'PercentageClassificationAssignedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageClassificationAssignedByVolume'
        /// </summary>
        [Test]
        public void PercentageClassificationAssignedByVolumeTest()
        {
            // TODO unit test for the property 'PercentageClassificationAssignedByVolume'
        }
        /// <summary>
        /// Test the property 'PercentageVolumeBaseQuantityAssignedByNumber'
        /// </summary>
        [Test]
        public void PercentageVolumeBaseQuantityAssignedByNumberTest()
        {
            // TODO unit test for the property 'PercentageVolumeBaseQuantityAssignedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageAreaBaseQuantityAssignedByNumber'
        /// </summary>
        [Test]
        public void PercentageAreaBaseQuantityAssignedByNumberTest()
        {
            // TODO unit test for the property 'PercentageAreaBaseQuantityAssignedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageLengthBaseQuantityAssignedByNumber'
        /// </summary>
        [Test]
        public void PercentageLengthBaseQuantityAssignedByNumberTest()
        {
            // TODO unit test for the property 'PercentageLengthBaseQuantityAssignedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageBaseQuantitiesAssignedByNumber'
        /// </summary>
        [Test]
        public void PercentageBaseQuantitiesAssignedByNumberTest()
        {
            // TODO unit test for the property 'PercentageBaseQuantitiesAssignedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageMaterialSpecifiedByNumber'
        /// </summary>
        [Test]
        public void PercentageMaterialSpecifiedByNumberTest()
        {
            // TODO unit test for the property 'PercentageMaterialSpecifiedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageMaterialSpecifiedByVolume'
        /// </summary>
        [Test]
        public void PercentageMaterialSpecifiedByVolumeTest()
        {
            // TODO unit test for the property 'PercentageMaterialSpecifiedByVolume'
        }
        /// <summary>
        /// Test the property 'PercentageElementsWithKnownMassByNumber'
        /// </summary>
        [Test]
        public void PercentageElementsWithKnownMassByNumberTest()
        {
            // TODO unit test for the property 'PercentageElementsWithKnownMassByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageElementsMappedByNumber'
        /// </summary>
        [Test]
        public void PercentageElementsMappedByNumberTest()
        {
            // TODO unit test for the property 'PercentageElementsMappedByNumber'
        }
        /// <summary>
        /// Test the property 'PercentageElementsMappedByVolume'
        /// </summary>
        [Test]
        public void PercentageElementsMappedByVolumeTest()
        {
            // TODO unit test for the property 'PercentageElementsMappedByVolume'
        }

    }

}
