/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductMatchTests
    {
        // TODO uncomment below to declare an instance variable for ProductMatch
        //private ProductMatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductMatch
            //instance = new ProductMatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductMatch
        /// </summary>
        [Test]
        public void ProductMatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductMatch
            //Assert.IsInstanceOfType<ProductMatch> (instance, "variable 'instance' is a ProductMatch");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'MatchType'
        /// </summary>
        [Test]
        public void MatchTypeTest()
        {
            // TODO unit test for the property 'MatchType'
        }

    }

}
