/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductTests
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Test]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Product
            //Assert.IsInstanceOfType<Product> (instance, "variable 'instance' is a Product");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }
        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Test]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }
        /// <summary>
        /// Test the property 'Circular'
        /// </summary>
        [Test]
        public void CircularTest()
        {
            // TODO unit test for the property 'Circular'
        }
        /// <summary>
        /// Test the property 'FixedDimensions'
        /// </summary>
        [Test]
        public void FixedDimensionsTest()
        {
            // TODO unit test for the property 'FixedDimensions'
        }
        /// <summary>
        /// Test the property 'DefaultDimensions'
        /// </summary>
        [Test]
        public void DefaultDimensionsTest()
        {
            // TODO unit test for the property 'DefaultDimensions'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
