/* 
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V11CreateBuildingFileElementRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V11CreateBuildingFileElementRequestTests
    {
        // TODO uncomment below to declare an instance variable for V11CreateBuildingFileElementRequest
        //private V11CreateBuildingFileElementRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V11CreateBuildingFileElementRequest
            //instance = new V11CreateBuildingFileElementRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V11CreateBuildingFileElementRequest
        /// </summary>
        [Test]
        public void V11CreateBuildingFileElementRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V11CreateBuildingFileElementRequest
            //Assert.IsInstanceOfType<V11CreateBuildingFileElementRequest> (instance, "variable 'instance' is a V11CreateBuildingFileElementRequest");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MaterialName'
        /// </summary>
        [Test]
        public void MaterialNameTest()
        {
            // TODO unit test for the property 'MaterialName'
        }
        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Test]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }
        /// <summary>
        /// Test the property 'ElementClass'
        /// </summary>
        [Test]
        public void ElementClassTest()
        {
            // TODO unit test for the property 'ElementClass'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Test]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Test]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Phase'
        /// </summary>
        [Test]
        public void PhaseTest()
        {
            // TODO unit test for the property 'Phase'
        }
        /// <summary>
        /// Test the property 'Classification'
        /// </summary>
        [Test]
        public void ClassificationTest()
        {
            // TODO unit test for the property 'Classification'
        }
        /// <summary>
        /// Test the property 'Floor'
        /// </summary>
        [Test]
        public void FloorTest()
        {
            // TODO unit test for the property 'Floor'
        }

    }

}
