<?php
/**
 * BuildingFileElementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BuildingFileElementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuildingFileElementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV11BuildingsByBuildingIdFilesByFileIdElementsByIdDelete
     *
     * Deletes an existing building file element..
     *
     */
    public function testApiV11BuildingsByBuildingIdFilesByFileIdElementsByIdDelete()
    {
    }

    /**
     * Test case for apiV11BuildingsByBuildingIdFilesByFileIdElementsByIdGet
     *
     * Gets a building file element by its identifier and building file identifier..
     *
     */
    public function testApiV11BuildingsByBuildingIdFilesByFileIdElementsByIdGet()
    {
    }

    /**
     * Test case for apiV11BuildingsByBuildingIdFilesByFileIdElementsByIdPut
     *
     * Updates an existing building file element..
     *
     */
    public function testApiV11BuildingsByBuildingIdFilesByFileIdElementsByIdPut()
    {
    }

    /**
     * Test case for apiV11BuildingsByBuildingIdFilesByFileIdElementsGet
     *
     * Gets a building file elements by its building file identifier..
     *
     */
    public function testApiV11BuildingsByBuildingIdFilesByFileIdElementsGet()
    {
    }

    /**
     * Test case for apiV11BuildingsByBuildingIdFilesByFileIdElementsPost
     *
     * Create a new building file element..
     *
     */
    public function testApiV11BuildingsByBuildingIdFilesByFileIdElementsPost()
    {
    }
}
