<?php
/**
 * MaterialApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MaterialApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MaterialApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdFinancialvaluesGet
     *
     * Gets the financial values of a material, for manual import mode..
     *
     */
    public function testApiV11MaterialsByIdFinancialvaluesGet()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdFinancialvaluesPost
     *
     * Adds a financial value for a material, for manual import mode..
     *
     */
    public function testApiV11MaterialsByIdFinancialvaluesPost()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdFinancialvaluesPut
     *
     * Replaces the financial values for a material, for manual import mode..
     *
     */
    public function testApiV11MaterialsByIdFinancialvaluesPut()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdGet
     *
     * Gets a material by its identifier..
     *
     */
    public function testApiV11MaterialsByIdGet()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdMatchesGet
     *
     * Gets the matches of a material..
     *
     */
    public function testApiV11MaterialsByIdMatchesGet()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdMatchesPost
     *
     * Adds a match for a material..
     *
     */
    public function testApiV11MaterialsByIdMatchesPost()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdMatchesPut
     *
     * Replaces the matches for a material..
     *
     */
    public function testApiV11MaterialsByIdMatchesPut()
    {
    }

    /**
     * Test case for apiV11MaterialsByIdPut
     *
     * Replaces a material..
     *
     */
    public function testApiV11MaterialsByIdPut()
    {
    }

    /**
     * Test case for apiV11MaterialsGet
     *
     * Gets all materials..
     *
     */
    public function testApiV11MaterialsGet()
    {
    }

    /**
     * Test case for apiV11MaterialsPost
     *
     * Adds a material..
     *
     */
    public function testApiV11MaterialsPost()
    {
    }
}
