<?php
/**
 * PortfolioFileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PortfolioFileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PortfolioFileApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesByIdDelete
     *
     * Deletes a portfolio file..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesByIdDelete()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesByIdDownloadGet
     *
     * Gets a download url for the portfolio file..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesByIdDownloadGet()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesByIdGet
     *
     * Gets a portfolio file by its identifier..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesByIdGet()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesByIdStatusGet
     *
     * Gets a portfolio file status by its identifier..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesByIdStatusGet()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesByIdUploadPost
     *
     * Uploads a portfolio file..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesByIdUploadPost()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesGet
     *
     * Gets all portfolio files for a portfolio..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesGet()
    {
    }

    /**
     * Test case for apiV11PortfoliosByPortfolioIdFilesPost
     *
     * Adds a portfolio file..
     *
     */
    public function testApiV11PortfoliosByPortfolioIdFilesPost()
    {
    }
}
