<?php
/**
 * ProductApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Madaster Private API
 *
 * The Madaster Private API endpoint.
 *
 * OpenAPI spec version: 1.1
 * Contact: service@madaster.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV11ProductsByIdChildrenGet
     *
     * Gets the children of a product..
     *
     */
    public function testApiV11ProductsByIdChildrenGet()
    {
    }

    /**
     * Test case for apiV11ProductsByIdChildrenPost
     *
     * Adds a child for a product..
     *
     */
    public function testApiV11ProductsByIdChildrenPost()
    {
    }

    /**
     * Test case for apiV11ProductsByIdChildrenPut
     *
     * Replaces the children for a product..
     *
     */
    public function testApiV11ProductsByIdChildrenPut()
    {
    }

    /**
     * Test case for apiV11ProductsByIdFinancialvaluesGet
     *
     * Gets the financial values of a product..
     *
     */
    public function testApiV11ProductsByIdFinancialvaluesGet()
    {
    }

    /**
     * Test case for apiV11ProductsByIdFinancialvaluesPost
     *
     * Adds a financial value for a product..
     *
     */
    public function testApiV11ProductsByIdFinancialvaluesPost()
    {
    }

    /**
     * Test case for apiV11ProductsByIdFinancialvaluesPut
     *
     * Replaces the financial values for a product..
     *
     */
    public function testApiV11ProductsByIdFinancialvaluesPut()
    {
    }

    /**
     * Test case for apiV11ProductsByIdGet
     *
     * Gets a product by its identifier..
     *
     */
    public function testApiV11ProductsByIdGet()
    {
    }

    /**
     * Test case for apiV11ProductsByIdMatchesGet
     *
     * Gets the matches of a product..
     *
     */
    public function testApiV11ProductsByIdMatchesGet()
    {
    }

    /**
     * Test case for apiV11ProductsByIdMatchesPost
     *
     * Adds a match for a product..
     *
     */
    public function testApiV11ProductsByIdMatchesPost()
    {
    }

    /**
     * Test case for apiV11ProductsByIdMatchesPut
     *
     * Replaces the matches for a product..
     *
     */
    public function testApiV11ProductsByIdMatchesPut()
    {
    }

    /**
     * Test case for apiV11ProductsByIdPut
     *
     * Replaces a product..
     *
     */
    public function testApiV11ProductsByIdPut()
    {
    }

    /**
     * Test case for apiV11ProductsGet
     *
     * Gets all products..
     *
     */
    public function testApiV11ProductsGet()
    {
    }

    /**
     * Test case for apiV11ProductsPost
     *
     * Adds a product..
     *
     */
    public function testApiV11ProductsPost()
    {
    }
}
